### ISSUE TITLE
Building error in eightshift internal boilerplate install

### ISSUE THREAD

**Issue by volfkarlo** [infinum/eightshift-blocks#4]
## Current Behavior

Exit with error while building assets.
Error: No mixin named grid-width-modifiers

## Expected Behavior

Finishing script without errors

## Possible Solution

In file public_html/eightshift-starter/wp-content/themes/eightshift-starter/src/blocks/wrapper/wrapper-style.scss (line 105, column 16)
change:
@include grid-width-modifiers($wrapper: #{$this}__inner);
to
@include flex-grid-width-modifiers($wrapper: #{$this}__inner);

## Steps to Reproduce (for bugs)

1. npx create-wp-projects
or
1. after the most of installation is set you want to build assets with npm run build

## Your Environment

* PHP version:
* Development environment: 
* Server type: 
* Operating System and version:

**Comment by iruzevic** [comment]
this is fixed
